#!/usr/bin/env bash

function checkScala {
    if [[ $SCALA_HOME != *[!\ ]* ]]
        then
            echo "setting environment variable to the result of which scala"
            export SCALA=$(which scala)
         else
            export SCALA="$SCALA_HOME/bin/scala"
    fi
    echo "using $SCALA"
}

function checkSBT {
    if [[ $SBT_HOME != *[!\ ]* ]]
        then
            echo "setting environment variable to the result of which sbt"
            export SBT=$(which sbt)
        else
            export SBT="$SBT_HOME/bin/sbt"

    fi
    echo "using $SBT"
}

function build {
    $SBT clean package
}

function start {
    checkScala
    checkSBT
    build
    $SBT "project creditApprovalService" "run"

}

function stop {
    echo "maybe use killall scala for this?"
    PROC=$(ps -ef | grep sbt | grep java | grep -v grep | awk '{print $2}')
    kill -15 $PROC
}

function restart {
    echo "ok"
}

OP=$1

if [ ! -z $OP ]
    then
            case $OP in
                start)
                    start
                    ;;
                stop)
                    stop
                    ;;
                restart)
                    restart
                    ;;
                *)
                    echo "Invalid operation name : $OP. Usage is ./run (start|stop|restart)"
                    exit 1
             esac
    else
        echo "You did not specify an operation, exiting"
        exit 1
fi